### ISSUE TITLE
NameError: name 'PngInfo' is not defined with fix

### ISSUE THREAD

**Issue by wolfden** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#10]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\Ai\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Ai\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Ai\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 669, in save_images
    metadata = PngInfo()
NameError: name 'PngInfo' is not defined

added **from PIL.PngImagePlugin import PngInfo**

resulted in the next error:
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\Ai\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Ai\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Ai\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 672, in save_images
    metadata.add_text("prompt", json.dumps(prompt))
NameError: name 'json' is not defined

added **import json**

All working again

**Comment by wolfden** [comment]
import torch
import numpy as np
from PIL import Image, ImageEnhance
from PIL.PngImagePlugin import PngInfo
import json
import os
import sys
import io
import pip

**Comment by NGC38** [comment]
I'm having this same error since yesterday update... Thanks for the fix...

**Comment by Suzie1** [comment]
Hi, we cleaned the libraries but may have removed one to many. We'll add back json and pnginfo. Thanks for reporting this. 
We'll add these back in the next update tomorrow. Suzie

**Comment by Suzie1** [comment]
We added back the two missing libraries in a patch tonight. Thanks again for reporting this. Suzie

**Comment by NGC38** [comment]
yw (obrigado eu :)
