### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy.controlnet'

### ISSUE THREAD

**Issue by luciancaetano** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#13]
ModuleNotFoundError: No module named 'comfy.controlnet'

Cannot import D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes module for custom nodes: No module named 'comfy.controlnet'
Registered sys.path: ['D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\comfy', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages\\git\\ext\\gitdb', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python310.zip', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\Scripts\\DLLs', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\Scripts\\lib', 'D:\\StabilityMatrix\\Data\\Assets\\Python310', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages\\win32', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages\\win32\\lib', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages\\Pythonwin', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\subpack', '../..']
Traceback (most recent call last):
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\pose.py", line 5, in <module>
    from .. import mp_pose_hand
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\mp_pose_hand\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by RockOfFire** [comment]
Hello!  Sorry about replying so late to this issue.  I think ComfyUI up-dated and added that comfy.controlnet file.  If you up-date comfyUI, that may be the solution.  If that doesn't work, let me know.  We will solve the issue together.  :D
