### ISSUE TITLE
Missing module 'halftone'

### ISSUE THREAD

**Issue by Arkhaner1511** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#2]
After the last update i got following error after starting ComfyUI with yout custom node:

 _Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 1, in <module>
    from .Comfyroll_Nodes import *
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 24, in <module>
    from halftone import halftone
ModuleNotFoundError: No module named 'halftone'_

**Comment by RockOfFire** [comment]
Oh!!!  Thank you for catching this.  I'll comment out that import now.

**Comment by RockOfFire** [comment]
Try it out now.  Let me know if you still get the error.

**Comment by Arkhaner1511** [comment]
No ... the error is gone. 👍 

Thanks for the super fast bug fixing!

**Comment by RockOfFire** [comment]
No problem!!  :D  Check out the Halftone Grid node sometime!  You can use it with image 2 image and there's so many different options.
