### ISSUE TITLE
VAE Decode Node raised an exception after installing Comfyroll

### ISSUE THREAD

**Issue by GeekChuan** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#20]
I tried to install Comfyroll by ComfyUI-Manager, but VAE Decode node raises an exception when i run the workflow as follows:

File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "/root/ComfyUI/comfy/sd.py", line 203, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples) + 1.0) / 2.0, min=0.0, max=1.0).cpu().float()
  File "/root/ComfyUI/comfy/ldm/models/autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 716, in forward
    h = self.mid.attn_1(h)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 295, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 193, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 291, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 307, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 96, in _dispatch_fw
    return _run_priority_list(
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 53, in _run_priority_list
    not_supported = op.not_supported_reasons(inp)
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/triton.py", line 118, in not_supported_reasons
    if _is_triton_available():
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/__init__.py", line 34, in func_wrapper
    value = func()
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/__init__.py", line 47, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/triton/__init__.py", line 12, in <module>
    from .dropout import FusedDropoutBias, dropout  # noqa
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/triton/dropout.py", line 13, in <module>
    import triton
  File "/root/miniconda3/lib/python3.10/site-packages/triton/__init__.py", line 20, in <module>
    from .runtime import (
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..compiler import OutOfResources
  File "/root/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 22, in <module>
    import setuptools
  File "/root/miniconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/root/miniconda3/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/root/miniconda3/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/root/miniconda3/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /root/miniconda3/lib/python3.10/distutils/core.py

**Comment by EvotisLab** [comment]
I'm having the same issue but not always. I haven't identified what makes it break. I mean on some cloud instances I don't have the issue.

But I can confirm the problem can happen with **ComfyRoll as the only custom node installed**, while running a **workflow in which none of the ComfyRoll nodes are even used** (the basic default for instance).… and the problem goes away if I simply remove ComfyRoll.
Confirmed with the latest update ro of ComfyUI at the time of writing, i.e. commit 4496f6a8adc9883adc74617b557c1de7b0e50104

!!! Exception during processing !!!
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 157, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 87, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 80, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "/workspace/ComfyUI/comfy/sd.py", line 204, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples) + 1.0) / 2.0, min=0.0, max=1.0).cpu().float()
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "/workspace/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 716, in forward
    h = self.mid.attn_1(h)
  File "/workspace/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 295, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 193, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 291, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 307, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 96, in _dispatch_fw
    return _run_priority_list(
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 53, in _run_priority_list
    not_supported = op.not_supported_reasons(inp)
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/ops/fmha/triton.py", line 118, in not_supported_reasons
    if _is_triton_available():
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/__init__.py", line 34, in func_wrapper
    value = func()
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/__init__.py", line 47, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/triton/__init__.py", line 12, in <module>
    from .dropout import FusedDropoutBias, dropout  # noqa
  File "/workspace/myenv/lib/python3.10/site-packages/xformers/triton/dropout.py", line 13, in <module>
    import triton
  File "/workspace/myenv/lib/python3.10/site-packages/triton/__init__.py", line 20, in <module>
    from .runtime import (
  File "/workspace/myenv/lib/python3.10/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics
  File "/workspace/myenv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..compiler import OutOfResources
  File "/workspace/myenv/lib/python3.10/site-packages/triton/compiler.py", line 22, in <module>
    import setuptools
  File "/workspace/myenv/lib/python3.10/site-packages/setuptools/__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/workspace/myenv/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/workspace/myenv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/workspace/myenv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /usr/lib/python3.10/distutils/core.py

**Comment by Suzie1** [comment]
Hi, sorry this is giving problems. I'll investigate this tomorrow.

**Comment by EvotisLab** [comment]
Thanks @Suzie1 
I just was what was proposed in the other thread about distutils/setuptools and saw these packages appear in my trace… maybe it's related?
(it would be consistent with the fact I'm not getting the error in all setups and hard to know what factors in)

**Comment by Suzie1** [comment]
Hi again, we have just done a fix for issue 21. Please can you let us know if the issue recurs after updating.
Many thanks for reporting this.

**Comment by EvotisLab** [comment]
It works now! Problem gone! Many thanks to you for fixing it 🙏🏻
