### ISSUE TITLE
No module named 'comfy.controlnet'

### ISSUE THREAD

**Issue by cyrly97** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#9]
G:\ComfyUI_windows_portable\python_embeded\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 1, in <module>
    from .Comfyroll_Nodes import *
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 16, in <module>
    import comfy.controlnet
ModuleNotFoundError: No module named 'comfy.controlnet'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes module for custom nodes: No module named 'comfy.controlnet'
Registered sys.path: ['G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'G:\\ComfyUI_windows_portable\\ComfyUI\\comfy', 'G:\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\git\\ext\\gitdb', 'G:\\ComfyUI_windows_portable\\ComfyUI', 'G:\\ComfyUI_windows_portable\\python_embeded\\python310.zip', 'G:\\ComfyUI_windows_portable\\python_embeded', 'G:\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages', 'G:\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\win32', 'G:\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\win32\\lib', 'G:\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\Pythonwin', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\subpack', '../..']

**Comment by sternd** [comment]
Also seeing this error from other workflow users as of recently.

```
C:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages_distutils_hack__init.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes__init.py", line 1, in <module>
    from .Comfyroll_Nodes import *
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 16, in <module>
    import comfy.controlnet
ModuleNotFoundError: No module named 'comfy.controlnet
```

**Comment by RockOfFire** [comment]
ComfyUI had an up-date on control nets.  To fix that error you'll need to up-date your ComfyUI.  The up-date happened 2 days ago.  Let me know if you are still getting any issues after.

**Comment by sternd** [comment]
Ok, I see what is causing the issue here. The latest release of the ComfyUI Windows Portable has not been updated since August 23rd (commit e3d0a9a) and as such is incompatible with your latest Comfyroll updates. Pulling the latest version of ComfyUI after installation does resolve the issue. I'll update my install scripts for the workflow to do an additional ComfyUI update to resolve this moving forwards.
